/*
 * frmNTerminais.java
 *
 * Created on October 17, 2005, 7:19 PM
 */

package gpa;

/**
 *
 * @author  Igor
 */
public class frmNTerminais extends javax.swing.JFrame {
    
    private java.util.Vector vetNTerminais;
    private javax.swing.JScrollPane scroll;
    
    /** Creates new form frmNTerminais */
    public frmNTerminais() {
        vetNTerminais = new java.util.Vector();
        initComponents();
        
        scroll = new javax.swing.JScrollPane(lstNTerminais);
        getContentPane().add(scroll);    
        scroll.setViewportView(lstNTerminais);
        scroll.setBounds(10, 90, 230, 90);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        btnAdicionaNTerminais = new javax.swing.JButton();
        lstNTerminais = new javax.swing.JList();
        txtSimbolo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        setTitle("N\u00e3o Terminais");
        btnAdicionaNTerminais.setFont(new java.awt.Font("Arial", 0, 10));
        btnAdicionaNTerminais.setText("Adicionar");
        btnAdicionaNTerminais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionaNTerminaisActionPerformed(evt);
            }
        });

        getContentPane().add(btnAdicionaNTerminais);
        btnAdicionaNTerminais.setBounds(10, 60, 100, 23);

        lstNTerminais.setMaximumSize(new java.awt.Dimension(10, 10));
        getContentPane().add(lstNTerminais);
        lstNTerminais.setBounds(10, 90, 230, 90);

        txtSimbolo.setColumns(1);
        txtSimbolo.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtSimboloInputMethodTextChanged(evt);
            }
        });
        txtSimbolo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSimboloKeyTyped(evt);
            }
        });
        txtSimbolo.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtSimboloCaretUpdate(evt);
            }
        });

        getContentPane().add(txtSimbolo);
        txtSimbolo.setBounds(10, 30, 230, 21);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 10));
        jLabel1.setText("Adicione os N\u00e3o Terminais");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 140, 13);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-258)/2, (screenSize.height-223)/2, 258, 223);
    }//GEN-END:initComponents

    private void btnAdicionaNTerminaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionaNTerminaisActionPerformed
        // TODO add your handling code here:
        if (!vetNTerminais.contains(txtSimbolo.getText())) {
            vetNTerminais.addElement(txtSimbolo.getText());
            lstNTerminais.setListData(vetNTerminais);
            txtSimbolo.setText("");
            txtSimbolo.grabFocus();
        }
    }//GEN-LAST:event_btnAdicionaNTerminaisActionPerformed

    private void txtSimboloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSimboloKeyTyped
        // TODO add your handling code here:
        String chr = String.valueOf(evt.getKeyChar());
        chr = chr.toUpperCase();               
        if ((txtSimbolo.getText().length()) < 1 && 
            (chr.charAt(0) >= 'A' && chr.charAt(0) <= 'Z'))
            evt.setKeyChar(chr.charAt(0));
        else {
            if (evt.getKeyText(evt.getKeyChar()) != "Backspace")            
                evt.setKeyChar('\0');
        }           
        
    }//GEN-LAST:event_txtSimboloKeyTyped

    private void txtSimboloCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtSimboloCaretUpdate
        // TODO add your handling code here:
       // txtSimbolo.setText(txtSimbolo.getText().toUpperCase());
    }//GEN-LAST:event_txtSimboloCaretUpdate

    private void txtSimboloInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtSimboloInputMethodTextChanged
        // TODO add your handling code here:
        //evt.getText().
        //txtSimbolo.getText().toUpperCase();        
    }//GEN-LAST:event_txtSimboloInputMethodTextChanged
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmNTerminais().setVisible(true);
            }
        });
    }
    
    public java.util.Vector getVetNTerminais() {
        return vetNTerminais;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionaNTerminais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList lstNTerminais;
    private javax.swing.JTextField txtSimbolo;
    // End of variables declaration//GEN-END:variables
    
}
