/*
 * frmProducoes.java
 *
 * Created on October 18, 2005, 8:55 PM
 */

package gpa;

/**
 *
 * @author  Igor
 */
public class frmProducoes extends javax.swing.JFrame {
    
    private java.util.Vector vetTerminais;
    private java.util.Vector vetNTerminais;
    private java.util.Vector producoes;
    private javax.swing.JScrollPane scroll;
    /** Creates new form frmProducoes */
    public frmProducoes() {
        initComponents();
        producoes = new java.util.Vector();
        
        scroll = new javax.swing.JScrollPane(lstProducoes);                
        getContentPane().add(scroll);    
        scroll.setViewportView(lstProducoes);
        scroll.setBounds(20, 110, 280, 120);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel1 = new javax.swing.JLabel();
        cmbProducao = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cmbTerminal = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cmbNTerminal = new javax.swing.JComboBox();
        btnAdicionar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lstProducoes = new javax.swing.JList();
        btnRemover = new javax.swing.JButton();

        getContentPane().setLayout(null);

        setTitle("Produ\u00e7\u00f5es");
        jLabel1.setFont(new java.awt.Font("Arial", 0, 10));
        jLabel1.setText("Produ\u00e7\u00e3o");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 50, 13);

        cmbProducao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProducaoActionPerformed(evt);
            }
        });

        getContentPane().add(cmbProducao);
        cmbProducao.setBounds(20, 30, 80, 21);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 10));
        jLabel2.setText("Terminal");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 10, 43, 13);

        getContentPane().add(cmbTerminal);
        cmbTerminal.setBounds(110, 30, 80, 21);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 10));
        jLabel3.setText("N\u00e3o Terminal");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 10, 80, 13);

        getContentPane().add(cmbNTerminal);
        cmbNTerminal.setBounds(200, 30, 80, 21);

        btnAdicionar.setFont(new java.awt.Font("Arial", 0, 10));
        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        getContentPane().add(btnAdicionar);
        btnAdicionar.setBounds(190, 60, 90, 23);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 10));
        jLabel4.setText("Produ\u00e7\u00f5es");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 90, 70, 13);

        getContentPane().add(lstProducoes);
        lstProducoes.setBounds(20, 110, 280, 120);

        btnRemover.setFont(new java.awt.Font("Arial", 0, 10));
        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        getContentPane().add(btnRemover);
        btnRemover.setBounds(330, 120, 90, 23);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-438)/2, (screenSize.height-273)/2, 438, 273);
    }//GEN-END:initComponents

    private void cmbProducaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProducaoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cmbProducaoActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:
        Producao producao = (Producao) lstProducoes.getSelectedValue();
        producoes.remove(producao);
        lstProducoes.setListData(producoes);  
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
        Producao producao = (Producao) getProducao((String) cmbProducao.getSelectedItem());
        Elemento elem = new Elemento((String) cmbTerminal.getSelectedItem(), 
                                    (String) cmbNTerminal.getSelectedItem());
        if (producao == null) 
            producao = new Producao((String) cmbProducao.getSelectedItem());            
        
        if (!producao.temElemento(elem))
            producao.add(elem);
        
        if (!producoes.contains(producao)) {            
            producoes.addElement(producao);
        } else {            
            producoes.setElementAt(producao, producoes.indexOf(producao));
        }
        
        lstProducoes.setListData(producoes);        
        
    }//GEN-LAST:event_btnAdicionarActionPerformed
    
    private Object getProducao(String _producao) {
        Producao producao;
        int i;        
        for (i=0;i < producoes.size(); i++) {
            producao = (Producao) producoes.get(i);
            if (producao.getProduto().equals(_producao)) {
                return producao;                
            }
        }
        return null;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmProducoes().setVisible(true);
            }
        });
    }
    
    public void setVetTerminais(java.util.Vector _vetTerminais) {
        vetTerminais = _vetTerminais;        
    }
    
    public void setVetNTerminais(java.util.Vector _vetNTerminais) {
        vetNTerminais = _vetNTerminais;        
    }
    
    public java.util.Vector getProducoes() {
        return producoes;
    }
    
    public void show() {
        super.show();
        int i;
        
        cmbTerminal.removeAllItems();
        for(i=0;(i < vetTerminais.size());i++)
            cmbTerminal.addItem(vetTerminais.get(i));
        
        cmbNTerminal.removeAllItems();
        cmbNTerminal.addItem("£");        
        for(i=0;(i < vetNTerminais.size());i++)
            cmbNTerminal.addItem(vetNTerminais.get(i));        
                
        cmbProducao.removeAllItems();        
        for(i=0;(i < vetNTerminais.size());i++)
            cmbProducao.addItem(vetNTerminais.get(i));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JComboBox cmbNTerminal;
    private javax.swing.JComboBox cmbProducao;
    private javax.swing.JComboBox cmbTerminal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList lstProducoes;
    // End of variables declaration//GEN-END:variables
    
}
