/*
 * frmTabelaTransicao.java
 *
 * Created on October 22, 2005, 10:00 PM
 */

package gpa;

/**
 *
 * @author  Henrique
 */
public class frmTabelaTransicao extends javax.swing.JFrame {
    
     private java.util.Vector producoes;     
     private java.util.Vector[][] transicoes;     
     private TabelaDeTransicao tabela;
     private Automato automato;    
     /** Creates new form frmTabelaTransicao */
    public frmTabelaTransicao() {
        initComponents();
        tblTransicoes.setModel(new javax.swing.table.DefaultTableModel(0,0));
        /*tblTransicoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));*/
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        cmbEstados = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        btnGerar = new javax.swing.JButton();
        lblTipo = new javax.swing.JLabel();
        btnTansformar = new javax.swing.JButton();
        btnMinimizar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        scrollTabela = new javax.swing.JScrollPane();
        tblTransicoes = new javax.swing.JTable();

        setTitle("Tabela de Transi\u00e7\u00e3o");
        jPanel1.setLayout(null);

        jPanel1.setPreferredSize(new java.awt.Dimension(0, 65));
        cmbEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadosActionPerformed(evt);
            }
        });

        jPanel1.add(cmbEstados);
        cmbEstados.setBounds(10, 30, 80, 21);

        jLabel1.setFont(new java.awt.Font("MS Sans Serif", 0, 10));
        jLabel1.setText("Estado Inicial");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 130, 14);

        btnGerar.setFont(new java.awt.Font("MS Sans Serif", 0, 10));
        btnGerar.setText("Gerar");
        btnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarActionPerformed(evt);
            }
        });

        jPanel1.add(btnGerar);
        btnGerar.setBounds(100, 30, 80, 23);

        lblTipo.setFont(new java.awt.Font("Arial", 1, 11));
        lblTipo.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(lblTipo);
        lblTipo.setBounds(350, 7, 30, 20);

        btnTansformar.setFont(new java.awt.Font("MS Sans Serif", 0, 10));
        btnTansformar.setText("Transformar");
        btnTansformar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTansformarActionPerformed(evt);
            }
        });

        jPanel1.add(btnTansformar);
        btnTansformar.setBounds(190, 30, 90, 23);

        btnMinimizar.setFont(new java.awt.Font("MS Sans Serif", 0, 10));
        btnMinimizar.setText("Minimizar");
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarActionPerformed(evt);
            }
        });

        jPanel1.add(btnMinimizar);
        btnMinimizar.setBounds(290, 30, 90, 23);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.BorderLayout());

        tblTransicoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollTabela.setViewportView(tblTransicoes);

        jPanel2.add(scrollTabela, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-408)/2, (screenSize.height-292)/2, 408, 292);
    }//GEN-END:initComponents

    private void btnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarActionPerformed
        // TODO add your handling code here:
        
        String vetTrans[][] = automato.getVetTrans();        
        automato.minimiza(vetTrans);
        
        vetTrans = automato.getVetTrans();
        criaJTabelaD(tabela.getSimbolos(), automato.getEstados(), vetTrans);
        
    }//GEN-LAST:event_btnMinimizarActionPerformed

    private void btnTansformarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTansformarActionPerformed
        // TODO add your handling code here:
        String vetTrans[][] = automato.determiniza();
        criaJTabelaD(tabela.getSimbolos(), automato.getEstados(), vetTrans);
        lblTipo.setText("AFD");
        //criaJTabela(tabela.getSimbolos(), tabela.getEstados());
        //lblTipo.setText(automato.getTipo());
    }//GEN-LAST:event_btnTansformarActionPerformed

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
        // TODO add your handling code here:
        //tblTransicoes = new javax.swing.JTable(getEstados((String) cmbEstados.getSelectedItem()), getSimbolos());
        //tblTransicoes = new javax.swing.JTable(null, getSimbolos());
        tabela = new TabelaDeTransicao(producoes, 
                        (String) cmbEstados.getSelectedItem());
        automato = new Automato(tabela);
        
        lblTipo.setText(automato.getTipo());
        if(lblTipo.getText().equals("AFND"))        
            criaJTabela(tabela.getSimbolos(), tabela.getEstados());
        else {
            String vetTrans[][] = automato.getTransicoesEmString();
            criaJTabelaD(tabela.getSimbolos(), automato.getEstados(), vetTrans);
        }
            
        
        
    }//GEN-LAST:event_btnGerarActionPerformed
   
    private void criaJTabelaD(java.util.Vector _simbolos, java.util.Vector _estados, String[][] vetTrans) {
        int i,j;
        int colunas = (_estados.size() * _simbolos.size()) + 1;
        int linhas = _estados.size() + 1;
        String[][] strtabela = new String[linhas][colunas];
        
        String[] header = new String[_simbolos.size() + 1];
        header[0] = "";
        for (i=1; i<=_simbolos.size();i++) {
            header[i] = (String) _simbolos.get(i-1);
        }
        
        tblTransicoes.setModel(new javax.swing.table.DefaultTableModel(
           strtabela, header           
        ));
        
        transicoes = tabela.getTransicoes();
        
        for (i=0;i<_estados.size();i++) {
            tblTransicoes.setValueAt(_estados.get(i) ,i,0);
        }
        
        for (i=0;i < vetTrans.length;i++){
            for (j=0;j < vetTrans[i].length;j++){
                tblTransicoes.setValueAt(vetTrans[i][j],i,j+1);
            }
        }
        
    }
    
    
    private void criaJTabela(java.util.Vector _simbolos, java.util.Vector _estados) {
        int i,j;
        int colunas = (_estados.size() * _simbolos.size()) + 1;
        int linhas = _estados.size() + 1;
        String[][] strtabela = new String[linhas][colunas];
        
        String[] header = new String[_simbolos.size() + 1];
        header[0] = "";
        for (i=1; i<=_simbolos.size();i++) {
            header[i] = (String) _simbolos.get(i-1);
        }
        
        tblTransicoes.setModel(new javax.swing.table.DefaultTableModel(
           strtabela, header           
        ));
        
        transicoes = tabela.getTransicoes();
        
        for (i=0;i<_estados.size();i++) {
            tblTransicoes.setValueAt(_estados.get(i) ,i,0);
        }
        
        for (i=0;i < transicoes.length;i++){
            for (j=0;j < transicoes[i].length;j++){
                tblTransicoes.setValueAt(transicoes[i][j],i,j+1);
            }
        }
        
    }
    
    public Automato getAutomato() {
        return automato;
    }
    
    public TabelaDeTransicao getTabela() {
        return tabela;
    }
    
    public void setProducoes(java.util.Vector _producoes) {
        producoes = _producoes;
    }
    
    public void show() {
        super.show();
        int i;
        
        cmbEstados.removeAllItems();        
        for(i=0;(i < producoes.size());i++)             
            cmbEstados.addItem(((Producao) producoes.get(i)).getProduto());        
            
    }
    
    private void cmbEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEstadosActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTabelaTransicao().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerar;
    private javax.swing.JButton btnMinimizar;
    private javax.swing.JButton btnTansformar;
    private javax.swing.JComboBox cmbEstados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JScrollPane scrollTabela;
    private javax.swing.JTable tblTransicoes;
    // End of variables declaration//GEN-END:variables
    
}
