/*
 * frmTerminais.java
 *
 * Created on October 18, 2005, 8:39 PM
 */

package gpa;

/**
 *
 * @author  Igor
 */
public class frmTerminais extends javax.swing.JFrame {
    
    private java.util.Vector vetTerminais;
    javax.swing.JScrollPane scroll;
    /** Creates new form frmTerminais */
    public frmTerminais() {
        vetTerminais = new java.util.Vector();         
        initComponents();
        
        scroll = new javax.swing.JScrollPane(lstTerminais);                
        getContentPane().add(scroll);    
        scroll.setViewportView(lstTerminais);
        scroll.setBounds(10, 90, 230, 90);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel1 = new javax.swing.JLabel();
        txtSimbolo = new javax.swing.JTextField();
        btnAdicionaNTerminais = new javax.swing.JButton();
        lstTerminais = new javax.swing.JList();

        getContentPane().setLayout(null);

        setTitle("Terminais");
        jLabel1.setFont(new java.awt.Font("Arial", 1, 10));
        jLabel1.setText("Adicione os Terminais");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 140, 13);

        txtSimbolo.setColumns(1);
        txtSimbolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSimboloActionPerformed(evt);
            }
        });
        txtSimbolo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSimboloKeyTyped(evt);
            }
        });

        getContentPane().add(txtSimbolo);
        txtSimbolo.setBounds(10, 30, 230, 21);

        btnAdicionaNTerminais.setFont(new java.awt.Font("Arial", 0, 10));
        btnAdicionaNTerminais.setText("Adicionar");
        btnAdicionaNTerminais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionaNTerminaisActionPerformed(evt);
            }
        });

        getContentPane().add(btnAdicionaNTerminais);
        btnAdicionaNTerminais.setBounds(10, 60, 100, 23);

        lstTerminais.setMaximumSize(new java.awt.Dimension(10, 10));
        getContentPane().add(lstTerminais);
        lstTerminais.setBounds(10, 90, 230, 90);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-258)/2, (screenSize.height-223)/2, 258, 223);
    }//GEN-END:initComponents

    private void txtSimboloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSimboloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSimboloActionPerformed

    private void btnAdicionaNTerminaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionaNTerminaisActionPerformed
        // TODO add your handling code here:
        if (!vetTerminais.contains(txtSimbolo.getText())) {
            vetTerminais.addElement(txtSimbolo.getText());
            lstTerminais.setListData(vetTerminais);
            txtSimbolo.setText("");
            txtSimbolo.grabFocus();
        }
    }//GEN-LAST:event_btnAdicionaNTerminaisActionPerformed

    private void txtSimboloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSimboloKeyTyped
        // TODO add your handling code here:
        String chr = String.valueOf(evt.getKeyChar());
        chr = chr.toLowerCase();               
        if (txtSimbolo.getText().length() < 1)
            evt.setKeyChar(chr.charAt(0));
        else {
            if (evt.getKeyText(evt.getKeyChar()) != "Backspace")            
                evt.setKeyChar('\0');
        }   
    }//GEN-LAST:event_txtSimboloKeyTyped
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTerminais().setVisible(true);
            }
        });
    }
    
    public java.util.Vector getVetTerminais() {
        return vetTerminais;        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionaNTerminais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList lstTerminais;
    private javax.swing.JTextField txtSimbolo;
    // End of variables declaration//GEN-END:variables
    
}
